export const products = [
  {
    id: 1,
    name: 'Apple iPhone 11 64GB (czarny)',
    actual_price: '2499',
    old_price: '2549',
    category: 'smartphone',
    shop: 'media_markt',
    details: {
      screen: '6.1 (828 x 1792, Dotykowy, IPS, Liquid Retina HD)',
      internal_storage: '64 GB',
      ram: '4 GB',
      camera: 'Tylny: 12 + 12 Mpix, Przedni: 12 Mpix',
      system: 'iOS 13',
    },
    img: 'https://prod-api.mediamarkt.pl/api/images/gallery_original/thumbnails/images/20/20982476/apple-iphone-11-czarny-1.jpg',
    link: 'https://mediamarkt.pl/telefony-i-smartfony/smartfon-apple-iphone-11-64gb-czarny-mhda3pm-a',
  },
  {
    id: 2,
    name: 'Smartfon APPLE iPhone 13 Pro 128GB Złoty MLVC3PM/A',
    actual_price: '5178',
    old_price: '',
    category: 'smartphone',
    shop: 'cortland',
    details: {
      screen: '6.1 (1170 x 2532, Dotykowy, OLED, Super Retina XDR)',
      internal_storage: '128 GB',
      ram: '6 GB',
      camera: 'Tylny: 12 + 12 + 12 Mpix, Przedni: 12 Mpix',
      system: 'iOS 15',
    },
    img: 'https://prod-api.mediamarkt.pl/api/images/gallery_545_400/thumbnails/images/21/21607266/apple-iphone-13-pro-zloty.jpg',
    link: 'https://mediamarkt.pl/telefony-i-smartfony/smartfon-apple-iphone-13-pro-128gb-zloty-mlvc3pm-a',
  },
  {
    id: 3,
    name: 'Laptop APPLE MacBook Air 13 M1/8GB/256GB SSD/INT/macOS Gwiezdna szarość MGN63ZE/A',
    actual_price: '4299',
    old_price: '4529',
    category: 'laptop',
    shop: 'media_markt',
    details: {
      screen: '13.3 (2560 x 1600, IPS)',
      internal_storage: '256 GB',
      ram: '8 GB',
      procesor: 'Apple M1',
      system: 'macOS Big Sur',
    },
    img: 'https://prod-api.mediamarkt.pl/api/images/gallery_original/thumbnails/images/21/21351596/apple-macbook-air-13-gwiezdna-szarosc-1.jpg',
    link: 'https://mediamarkt.pl/komputery-i-tablety/laptop-apple-macbook-air-13-m1-8gb-256gb-ssd-int-macos-gwiezdna-szarosc-mgn63ze-a',
  },
  {
    id: 4,
    name: 'Apple iPhone 11 64GB (czarny)',
    actual_price: '2499',
    old_price: '2549',
    category: 'smartphone',
    shop: 'media_markt',
    details: {
      screen: '6.1 (828 x 1792, Dotykowy, IPS, Liquid Retina HD)',
      internal_storage: '64 GB',
      ram: '4 GB',
      camera: 'Tylny: 12 + 12 Mpix, Przedni: 12 Mpix',
      system: 'iOS 13',
    },
    img: 'https://prod-api.mediamarkt.pl/api/images/gallery_original/thumbnails/images/20/20982476/apple-iphone-11-czarny-1.jpg',
    link: 'https://mediamarkt.pl/telefony-i-smartfony/smartfon-apple-iphone-11-64gb-czarny-mhda3pm-a',
  },
  {
    id: 5,
    name: 'Laptop APPLE MacBook Air 13 M1/8GB/256GB SSD/INT/macOS Gwiezdna szarość MGN63ZE/A',
    actual_price: '4299',
    old_price: '4529',
    category: 'laptop',
    shop: 'rtv_euro_agd',
    details: {
      screen: '13.3 (2560 x 1600, IPS)',
      internal_storage: '256 GB',
      ram: '8 GB',
      procesor: 'Apple M1',
      system: 'macOS Big Sur',
    },
    img: 'https://prod-api.mediamarkt.pl/api/images/gallery_original/thumbnails/images/21/21351596/apple-macbook-air-13-gwiezdna-szarosc-1.jpg',
    link: 'https://mediamarkt.pl/komputery-i-tablety/laptop-apple-macbook-air-13-m1-8gb-256gb-ssd-int-macos-gwiezdna-szarosc-mgn63ze-a',
  },
  {
    id: 6,
    name: 'Apple iPhone 11 64GB (czarny)',
    actual_price: '2499',
    old_price: '2549',
    category: 'smartphone',
    shop: 'media_markt',
    details: {
      screen: '6.1 (828 x 1792, Dotykowy, IPS, Liquid Retina HD)',
      internal_storage: '64 GB',
      ram: '4 GB',
      camera: 'Tylny: 12 + 12 Mpix, Przedni: 12 Mpix',
      system: 'iOS 13',
    },
    img: 'https://prod-api.mediamarkt.pl/api/images/gallery_original/thumbnails/images/20/20982476/apple-iphone-11-czarny-1.jpg',
    link: 'https://mediamarkt.pl/telefony-i-smartfony/smartfon-apple-iphone-11-64gb-czarny-mhda3pm-a',
  },
  {
    id: 7,
    name: 'Smartfon APPLE iPhone 13 Pro 128GB Złoty MLVC3PM/A',
    actual_price: '5178',
    old_price: '',
    category: 'smartphone',
    shop: 'rtv_euro_agd',
    details: {
      screen: '6.1 (1170 x 2532, Dotykowy, OLED, Super Retina XDR)',
      internal_storage: '128 GB',
      ram: '6 GB',
      camera: 'Tylny: 12 + 12 + 12 Mpix, Przedni: 12 Mpix',
      system: 'iOS 15',
    },
    img: 'https://prod-api.mediamarkt.pl/api/images/gallery_545_400/thumbnails/images/21/21607266/apple-iphone-13-pro-zloty.jpg',
    link: 'https://mediamarkt.pl/telefony-i-smartfony/smartfon-apple-iphone-13-pro-128gb-zloty-mlvc3pm-a',
  },
];
